### ISSUE TITLE
It is not possible to turn the powerwall on / off

### ISSUE THREAD

**Issue by fighterzg6** [datMaffin/homebridge-tesla-powerwall#11]
Hello,I can not turn powerwall 2 on or off via homekit despite user and password

**Comment by datMaffin** [comment]
Hi, yeah when I started with this homebridge plugin there was no login required. Then there was an update that changed it to require one. I then simply guessed and implemented a default http login as a prefix: https://github.com/datMaffin/homebridge-tesla-powerwall/blob/master/index.js#L68

I never had the ability to test if it would work..

**Comment by fighterzg6** [comment]
can you change it to https?????

**Comment by datMaffin** [comment]
If your setting for the port is an empty string it should use https. I probably should add that an undefined port should also default to an https.

**Comment by datMaffin** [comment]
UPDATE: The documentation needed for providing the on/off functionality is getting added to https://github.com/vloschiavo/powerwall2

**Comment by datMaffin** [comment]
While the documentation was updated I cant seem to find the section where the login process is described.

I also do not really see a point why someone would want to turn off their powerwall.

As a result I am going to remove corresponding documentation to hide this functionality (which will continue to work for anyone who has Version < 1.20 installed on his powerwall)
