### ISSUE TITLE
Improve documentation of `ip`-field (Orig: Does not work with version 1.34.2?)

### ISSUE THREAD

**Issue by Praktiker** [datMaffin/homebridge-tesla-powerwall#13]
I really would like to use the plugin, it also appears in the HomeKit app but says: no answer or e.g. Grid Feed (not supported). Any ideas?

**Comment by Praktiker** [comment]
Sorry, it needs the IP, otherwise it seems not to work. So don't mind my comment. :-)

**Comment by datMaffin** [comment]
No problem; yeah the `ip` field is listed in the optional documentation section. The reasoning is that the `ip` field has a default value of `127.0.0.1` (localhost). However, using localhost as the default does not make much sense in practice.

- [ ] Improve documentation: The `ip` field should move from the optional to the mandatory section. 
- [ ] Maybe(?): Remove default value from implementation.
