### ISSUE TITLE
EHOSTUNREACH Error

### ISSUE THREAD

**Issue by cjastennett** [datMaffin/homebridge-tesla-powerwall#16]
Hi,

I am continuously getting the following error - any idea:

[4/22/2020, 9:32:54 PM] [Tesla Powerwall] status code:  undefined
[4/22/2020, 9:32:54 PM] [Tesla Powerwall] body:  undefined
[4/22/2020, 9:32:54 PM] [Tesla Powerwall] error:  Error: connect EHOSTUNREACH 192.168.xx.xx:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.xx.xx',
  port: 80
}

Thanks

**Comment by datMaffin** [comment]
Try removing the port setting; i.e. set `"port": ""`.

**Comment by cjastennett** [comment]
Thanks - already made that modification - json excerpt here:

{
            "platform": "TeslaPowerwall",
            "name": "Tesla Powerwall",
            "ip": "192.168.xx.xx",
            "lowBattery": 5,
            "additionalServices": {
                "powerwall": {
                    "homekitVisual": false,
                    "eveHistory": false,
                    "batteryIsLowSwitch": false,
                    "batteryIsChargingSwitch": false
                },
                "solar": {
                    "homekitVisual": true,
                    "evePowerMeter": false,
                    "eveHistory": false,
                    "eveLineGraph": false
                },
                "grid": {
                    "homekitVisual": false,
                    "positiveEvePowerMeter": false,
                    "negativeEvePowerMeter": false,
                    "eveHistory": false,
                    "eveLineGraph": false
                },
                "battery": {
                    "homekitVisual": false,
                    "positiveEvePowerMeter": false,
                    "negativeEvePowerMeter": false,
                    "eveHistory": false,
                    "eveLineGraph": false
                },
                "home": {
                    "homekitVisual": true,
                    "evePowerMeter": false,
                    "eveHistory": false,
                    "eveLineGraph": false
                },
                "gridstatus": {
                    "gridIsDownSwitch": false,
                    "gridIsUpSwitch": false,
                    "gridIsNotYetInSyncSwitch": false
                }
            }
        }

**Comment by datMaffin** [comment]
Hmm. 

A few ideas/questions; I am also going to include the (fairly) obvious stuff:
- Does the plugin partially work?
- Did you restart Homebridge after changing the config?
- Are you able to access the regular Tesla-Powerwall WebUI via the ip adress?
  * What does your browser do if you enter "http://*tesla-powerwall-ip*/api/meters/aggregates"?
    It should return a json text document.
  * How about "http://*tesla-powerwall-ip*/api/system_status/soe"? It should return a json text document.
  * How about "http://*tesla-powerwall-ip*/api/meters/aggregates"? It should return a json text document.
  * Does it work with explicitly using https: "https://*tesla-powerwall-ip*/api/meters/aggregates"?
- You can try executing Homebridge in debug mode (should be the command line option `-D`). When executing Homebridge in debug mode the amount of printout for debugging is greatly increased.

**Comment by cjastennett** [comment]
Thanks for this.

Interesting;y the solution was to remove the fixed IP mapping (Bind IP to MAC) for my Tesla Powerwall in my router. For some reason, the Tesla Powerwall did not like this. After a subsequent reboot of the router (note that a reboot of the router had not worked standlone earlier), the Powerwall reconnected to the network and allowed access for the homebridge plugin. Note that the Tesla app was working fine the whole time, but the web interface was not - so it was just the http/https portal that was not functioning. Strange, I but I have heard that some devices don't like a "Bind IP to MAC" forcing function sometimes. Anyway, is working now - Thanks for your help.

**Comment by datMaffin** [comment]
No problem.

Thanks for reporting back your solution.
