### ISSUE TITLE
Home App showing Not Unsupported 

### ISSUE THREAD

**Issue by acuraxl** [datMaffin/homebridge-tesla-powerwall#17]
I just installed this plugin and getting Not Support for Battery Charge and Grid Feed Accessory in the Apple Home App.   All the Flow Accessory showing up normally with Fan icon.

**Comment by datMaffin** [comment]
You can disable the accessories only supported by the Eve.app:
https://github.com/datMaffin/homebridge-tesla-powerwall#using-only-homeapp-supported-services-all-the-visualization-services

**Comment by acuraxl** [comment]
That is the config i'm using, i even reset it the homebridge and remove and readded into home app but its still showing up

**Comment by acuraxl** [comment]
This the config i'm using 

       {
            "platform": "TeslaPowerwall",
            "name": "Tesla Powerwall",
            "ip": "192.168.x.x",
            "pollingInterval": 10000,
            "historyInterval": 120000,
            "lowBattery": 10,
            "historySetting": {
                "storage": "fs"
            },
            "additionalServices": {
                "powerwall": {
                    "eveHistory": false
                },
                "solar": {
                    "evePowerMeter": false,
                    "eveHistory": false
                },
                "grid": {
                    "positiveEvePowerMeter": false,
                    "negativeEvePowerMeter": false,
                    "eveHistory": false
                },
                "battery": {
                    "positiveEvePowerMeter": false,
                    "negativeEvePowerMeter": false,
                    "eveHistory": false
                },
                "home": {
                    "evePowerMeter": false,
                    "eveHistory": false
                }
            }

**Comment by datMaffin** [comment]
Hmm... I see the same behavior on my end... 

I am now investigating.

**Comment by acuraxl** [comment]
Thanks for looking into it

**Comment by datMaffin** [comment]
You can install the fix with `npm install -g homebridge-tesla-powerwall@1.0.1-Beta`.

I had a typo in my code. I wrote `negativeRvePowerMeter` instead of `negativeEvePowerMeter`.

Thanks for reporting this issue!
