### ISSUE TITLE
Characteristics Warnings being Output to the Log

### ISSUE THREAD

**Issue by Vortec4800** [datMaffin/homebridge-tesla-powerwall#22]
After upgrading to Homebridge 1.3, it seems like there are some changes to characteristics such that the errors spam the console logs over and over every few seconds. It seems like the old values still work, it's just a logging issue at this point, but they may stop working with a future version.

```
[23/02/2021, 14:41:45] [homebridge-tesla-powerwall] This plugin generated a warning from the characteristic 'Battery Level': characteristic value expected number and received undefined. See https://git.io/JtMGR for more info.
[23/02/2021, 14:41:55] [homebridge-tesla-powerwall] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
```

There may be others with accessories/features I'm not using, but these are the two I see. Just wanted to put this on your radar, if it's not there already.

**Comment by datMaffin** [comment]
My guess would be that a fix similar to what was needed for #12 will suffice.

Need to check if the homebridge documentation mentions which characteristics are now considered to be essential.

**Comment by cjastennett** [comment]
HI, fantastic plugin - but with constinuoeus streams of warning and now it seems to have stopped showing reliable information I have had to remove it from my setup. Is there any chance of an update soon. Thanks.

**Comment by datMaffin** [comment]
The problem regarding reliable information is most likely related to #21

**Comment by datMaffin** [comment]
Turns out my initial guess was wrong. This issue was strongly linked with #21 (because of the failing authentication there was a new (unhandled/not considered) path in the code that resulted in undefined values being set).

See #21 for general authentication support.
