### ISSUE TITLE
Transfer to ioBroker

### ISSUE THREAD

**Issue by mubenab1107** [datMaffin/homebridge-tesla-powerwall#27]
in V1.x it was possible to transfer the data points from Tesla Powerwall to ioBroker due wrapping modus of homebridge-tesla-powerwall in a iobroker.ham. instanc.
Unfortunately, this no longer works in V2. Does anyone already have a workaround?

**Comment by datMaffin** [comment]
There should not have been any "breaking" changes that relate to this. (I am not sure what this iobroker is, though)

Breaking changes introduced were:
* the introduction of authentication 
* the usage of `https` instead of `http` url to communicate with the powerwall

**Comment by mubenab1107** [comment]
now I have set up everything fresh again. The transfer of Powerwall data points to ioBroker works now very well. I had to update the Homebridge accessories manager ham to 4.01. ioBroker

**Comment by datMaffin** [comment]
This issue then seems to have resolved itself.
