### ISSUE TITLE
Regular Warning message Undefined characteristic

### ISSUE THREAD

**Issue by gdotp01** [datMaffin/homebridge-tesla-powerwall#34]
A great plugin, thanks for writing it.
I recently updated a few dependencies and I’m now getting an u defined characteristic  warning regularly in the homebridge logs. 

Homebridge 1.3.8
Node 16.13.1
Non 8.1.2

![29F244BA-9F54-4B6D-937B-82C4D5EA1A4B](https://user-images.githubusercontent.com/50060482/145116533-af02c5c2-c3f1-411c-b4f1-4e9fe85099bc.jpeg)

**Comment by datMaffin** [comment]
I am guessing that the following characteristic is triggering the warning:
https://github.com/datMaffin/homebridge-tesla-powerwall/blob/fe71c940a22e67689822e1f6ec139f22cbef7952/src/accessories/powermeter.js#L80-L83

However, the code looks like it can not return undefined:

Characteristic is defined here:
https://github.com/datMaffin/homebridge-tesla-powerwall/blob/fe71c940a22e67689822e1f6ec139f22cbef7952/index.js#L493-L505

Message seems to be created by this code:
https://github.com/homebridge/HAP-NodeJS/blob/03431b8f93137f4c969888a3d631f52da5b787b6/src/lib/Characteristic.ts#L1966-L1969

**Comment by gdotp01** [comment]
Thanks for getting back. I’m on v2.2.0 of the plug-in which is the latest I think.

**Comment by gdotp01** [comment]
Hello.Any updates as to what is causing this? The warning is signalled just under every hour in the log file.

**Comment by datMaffin** [comment]
I currently do not have a good setup for testing and debugging.

However, I took a second look at my notes. I noticed that it *is* pretty likely that

> 
> https://github.com/datMaffin/homebridge-tesla-powerwall/blob/fe71c940a22e67689822e1f6ec139f22cbef7952/src/accessories/powermeter.js#L159-L163
> 

actually does contain a bug. The callback takes `(error, value)` as arguments. Meaning that the calculation is passed to the error field, while the `value` field will be `undefined`.

In the following days, I will try to prepare a version that should fix this issue, which can then be installed for testing purposes.

**Comment by gdotp01** [comment]
Great thanks. I can test it if you need

**Comment by datMaffin** [comment]
There is now a version uploaded to npm that contains the change that may fix this issue.
Use `sudo npm install -g homebridge-tesla-powerwall@3.0.0-Beta` to install it.

**Comment by gdotp01** [comment]
Ok I’ll give it a try. Thanks

**Comment by gdotp01** [comment]
All seems to be working well.

**Comment by datMaffin** [comment]
Ok. Thanks for reporting back 👍
