### ISSUE TITLE
403 before login complete

### ISSUE THREAD

**Issue by cda0011** [datMaffin/homebridge-tesla-powerwall#36]
Hi,

It seems that the plugin attempts to invoke the powerwall API before the login completes ... (see below)
I've verified the credentials are correct using https://github.com/vloschiavo/powerwall2/blob/master/samples/powerwallstats.sh

The plugin is partially working ... the Battery Charge and Grid Feed accessories are market as not supported

`
[1/18/2022, 9:50:55 AM] [Tesla Powerwall] Unexpected response: 403 User does not have adequate access rights
[1/18/2022, 9:50:55 AM] [Tesla Powerwall] Unexpected response: 403 User does not have adequate access rights
[1/18/2022, 9:50:55 AM] [Tesla Powerwall] Login successful
`

**Comment by datMaffin** [comment]
Yes, it trying to fetch data before the login is successful is not that great. (Though it should not be that critical either.)

About Battery Charge and Grid Feed shown as not supported: Those are probably the Eve.app services that Home.app does not support. Some of them are enabled by default, but they can be disabled (see https://github.com/datMaffin/homebridge-tesla-powerwall#configuration )

See also: #26

**Comment by cda0011** [comment]
thanks for the quick response and the plugin
