### ISSUE TITLE
Config Issues?

### ISSUE THREAD

**Issue by PBXLthrMan** [datMaffin/homebridge-tesla-powerwall#41]
Hello,

I'm trying to configure my PowerWall plugin, and I keep getting a JSON error when I click save, I can't figure out what's going on?

TIA.

{
            "platform": "TeslaPowerwall",
            "name": "Tesla Powerwall",
            "ip": "10.X.X.X",
            "username": "customer",
            "email": "cjxxxx@xx.com",
            "password": "XXXXXX",
            "loginInterval": 39600000,
            "pollingInterval": 15000,
            "historyInterval": 300000,
            "lowBattery": 20,
            "additionalServices": {
                "powerwall": {
                    "homekitVisual": true,
                    "eveHistory": true,
                    "batteryIsLowSwitch": false,
                    "batteryIsChargingSwitch": false,
                    "makeOnOffSwitchReadOnly": true
                },
                "solar": {
                    "homekitVisual": true,
                    "evePowerMeter": true,
                    "eveHistory": true,
                    "eveLineGraph": false,
                    "pullingFromSensor": false,
                    "sensorThreshold": 0
                },
                "grid": {
                    "homekitVisual": true,
                    "positiveEvePowerMeter": true,
                    "negativeEvePowerMeter": true,
                    "eveHistory": true,
                    "eveLineGraph": false,
                    "feedingToSensor": false,
                    "pullingFromSensor": false,
                    "sensorThreshold": 0
                },
                "battery": {
                    "homekitVisual": true,
                    "positiveEvePowerMeter": true,
                    "negativeEvePowerMeter": true,
                    "eveHistory": true,
                    "eveLineGraph": false,
                    "feedingToSensor": false,
                    "pullingFromSensor": false,
                    "sensorThreshold": 0
                },
                "home": {
                    "homekitVisual": true,
                    "evePowerMeter": true,
                    "eveHistory": true,
                    "eveLineGraph": false,
                    "feedingToSensor": false,
                    "sensorThreshold": 0
                },
                "gridstatus": {
                    "gridIsDownSwitch": false,
                    "gridIsUpSwitch": false,
                    "gridIsNotYetInSyncSwitch": false,
                    "gridIsDownSensor": false,
                    "gridIsUpSensor": false
                }
            }

**Comment by PBXLthrMan** [comment]
That helped. Thank you so much. Now I just have to figure out why the PowerWalls, despite being shown successfully on my WiFi network are not accessible.

"Error: connect EHOSTUNREACH 10.X.X.X:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '10.X.X.X',
  port: 443

**Comment by PBXLthrMan** [comment]
@datMaffin Follow-up question, if we leverage an automation to turn on our PowerWall (for example, to activate them during the night), A) will that work the way I'm hoping and B) does it impact our grid connectivity if we drain the PowerWall battery?
![Screenshot 2022-06-08 at 5 04 40 PM](https://user-images.githubusercontent.com/90646855/172717195-98dfb490-6236-4764-a386-29ac81a40031.png)

**Comment by datMaffin** [comment]
I am not entirely sure what "switching the Powerwall off" exactly means. However, I would guess that when the Powerwall is switched off that it will stop both getting charged or discharged. It will therefore probably not make much sense to switch it off (which is also one of the reasons that the switch will by default do nothing).

**Comment by PBXLthrMan** [comment]
@datMaffin Thanks for the additional information, what I am trying to do is control when the PowerWalls power my house, because the default options in the Tesla app don't provide the granular specifics regarding allowing a time-frame (for example from 3am to 7am) to shut off the grid power and use the PowerWalls. Does that make sense? Thus, I am wondering if any of the HomeKit integration options can provide for that functionality.

**Comment by datMaffin** [comment]
Ah. Yeah, that is not yet supported: Related issues are #37 and #15

**Comment by datMaffin** [comment]
I guess I can close this. Feel free to reopen if you have a related issue.
