### ISSUE TITLE
What does the gridIsNotYetInSyncSwitch option do?

### ISSUE THREAD

**Issue by parsap** [datMaffin/homebridge-tesla-powerwall#46]
I was hoping some documentation for the "gridIsNotYetInSyncSwitch" switch could be added.

**Comment by datMaffin** [comment]
Not entirely sure. It is basically just what the Powerwall returns.

However, based on the context of there being the states:
* SystemGridConnected
* SystemIslandedActive
* SystemTransitionToGrid

it sounds like it is an intermediate state that is reached when Islanded was active and it is now in the process of connecting to the grid.
However, connecting to the grid is not trivial, as it needs to first have the same phase as the grid. The reason being that the electrical grid use alternating current, so it would be bad for the Powerwall and the Grid to not be in sync first.


If anyone else has a better explanation feel free to add it here.
