### ISSUE TITLE
Battery Charge and Grid Feed, not supported

### ISSUE THREAD

**Issue by pponce** [datMaffin/homebridge-tesla-powerwall#7]
First just wanted to say this is awesome.  
Just happened to find this plugin. So great to see the battery status and the data in the Home app.

I installed everything without a hitch.
However in the apple Home app i see two "buttons". "Battery Charge" and "Grid feed". They both show as Not supported in the home app. Is this expected behavior? or do i have a setting that is off in my config.
thanks!

**Comment by datMaffin** [comment]
Probably the same as #13
