### ISSUE TITLE
Change tariffs?

### ISSUE THREAD

**Issue by DanielO** [datMaffin/homebridge-tesla-powerwall#9]
Hi,
How do you change the tariffs for power that it uses to calculate total cost etc?

I had a look in the Eve app and the plugin source but can't work it out.

Thanks

**Comment by datMaffin** [comment]
Sorry for answering so late.

To be honest I never really got the hang of all the features of the eve app (I had no real documentation). I believe I tried to implement everything I could find.

**Comment by DanielO** [comment]
No problem, thanks for getting back to me.

I had more of a look in the app and couldn't figure it out either, perhaps there is some other way but for now just the kW[hr] usage numbers are great.

Thanks!
